# Generated by Django 4.2.29 on 2026-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100, unique=True)),
                ('emplacement', models.CharField(max_length=100)),
                ('puissance_kw', models.FloatField()),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('maintenance', 'En maintenance')], max_length=20)),
                ('date_installation', models.DateField()),
            ],
        ),
    ]
