# Generated by Django 4.2.29 on 2026-05-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borne', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConnecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('vitesse_charge', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('duree_minutes', models.IntegerField()),
                ('energie_kwh', models.FloatField()),
                ('borne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borne.borne')),
            ],
        ),
        migrations.AddField(
            model_name='borne',
            name='connecteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='borne.typeconnecteur'),
        ),
    ]
