# Generated by Django 4.2.29 on 2026-05-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borne', '0002_typeconnecteur_sessioncharge_borne_connecteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borne',
            name='connecteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borne.typeconnecteur'),
        ),
        migrations.AlterField(
            model_name='typeconnecteur',
            name='vitesse_charge',
            field=models.CharField(choices=[('rapide', 'Rapide'), ('standard', 'Standard')], max_length=20),
        ),
    ]
